### ISSUE TITLE
json-stream-0.3.0.1 does not compile

### ISSUE THREAD

**Issue by peti** [ondrap/json-stream#1]
Citing from http://hydra.cryp.to/build/778766/nixlog/2/raw:

    c_lib/lexer.c: In function ‘handle_string’:

    c_lib/lexer.c:182:5:
         error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (char ch=input[lexer->position]; lexer->position < lexer->length && safechar(ch); ch = input[++lexer->position])
             ^

    c_lib/lexer.c:182:5:
         note: use option -std=c99 or -std=gnu99 to compile your code

**Comment by ondrap** [comment]
Thanks for the report, I didn't test it on Linux (which I did about an hour ago). It is already fixed in git, I will publish a new version tonight (with one more bugfix).
