### ISSUE TITLE
Memory leak in arrayOf and friends 

### ISSUE THREAD

**Issue by edsko** [ondrap/json-stream#10]
Suppose we have a large file

``` javascript
{"k1":1
,"k2":2
...
,"k999999":999999
,"k1000000":1000000
}
```

(about a 17M .json file) and we try to parse it as follows:

``` haskell
import Data.JsonStream.Parser
import qualified Data.ByteString.Lazy as BS.L

test :: FilePath -> IO ()
test fp = do
    inp <- BS.L.readFile fp
    let out = parseLazyByteString (objectItems (integer :: Parser Int)) inp
    mapM_ print out
```

This works beautifully; the whole thing runs in a constant 300 kB. Nice :smile:

But now let's swap that big object for a big array instead:

``` javascript
[1
,2
,3
...
,999999
,1000000
]
```

(slightly smaller .json file, about 7.6MB), and we try to parse this in the same way:

``` haskell
test :: FilePath -> IO ()
test fp = do
    inp <- BS.L.readFile fp
    let out = parseLazyByteString (arrayOf (integer :: Parser Int)) inp
    mapM_ print out
```

All of a sudden we have a huge 20MB memory leak :-(

**Comment by edsko** [comment]
(Incidentally,  in my actual code I'm working with `ParseOutput` directly, and am not using any lazy bytestrings, but that has the same problem.)

**Comment by ondrap** [comment]
That's quite interesting - when I compile the same program directly in the `json-stream` directory, it doesn't leak. When I use it as a dependency project, it leaks.

**Comment by edsko** [comment]
Nice find, thanks for the fix! Just something I noticed when I looked at the patch: perhaps a bang on the wildcard in the first case of nextItem might help ghc infer that this function truly really is strict in that argument? Note sure if it would make any real difference, but it might.
