### ISSUE TITLE
Stackage?

### ISSUE THREAD

**Issue by michaelt** [ondrap/json-stream#11]
This is an unimportant request, but I have a (somewhat speculative) package that depends on this one and would like to get it to build with stackage. This of course requires that the things it depends on are on stackage too. This just involves sending a correctly formatted pull request modifying [`build-constraints.yaml`](https://github.com/fpco/stackage/blob/master/build-constraints.yaml) like this one from 12 hours ago https://github.com/fpco/stackage/commit/102e4eca86e55cec7930328e46fb76639e84ae96 I don't myself use stack/stackage much - mostly just to make sure everything builds with it.

**Comment by ondrap** [comment]
I have added the pull request https://github.com/fpco/stackage/pull/1904

**Comment by michaelt** [comment]
Thanks!
