### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by torgeirsh** [ondrap/json-stream#13]
I get the following error when trying to install with stack:
```
    C:\Users\???\AppData\Local\Temp\stack8052\json-stream-0.4.1.2\c_lib\lexer.c:5:21: error:
         fatal error: sys/uio.h: No such file or directory
    compilation terminated.
    `gcc.exe' failed in phase `C Compiler'. (Exit code: 1)
```
Is it possible to work around the platform specific header file?

**Comment by ondrap** [comment]
The `master` branch had some not-yet-official changes, so I rolled them back and applied your patch. I was working on the issue #12 and I don't have this worked out yet. I will push the new version to hackage as soon as it compiles.
