### ISSUE TITLE
Select second element of a list and LocalTime

### ISSUE THREAD

**Issue by Ulrar** [ondrap/json-stream#19]
Hi,

I realize this is a bit dumb, but I need to select only the second (which should also be the last) element of a list.

For example : 

    "columns": ["time","active"]

I currently get those two values in a list (using arrayOf $ "columns" .: value), then I discard "time". Just wondering if there is a way to get only "active" directly.

And as a bonus question, is there any way to parse LocalTime or UTCTime (or something similar) directly ? I currently make the API return a timestamp and convert from there, just wondering if there might be a way to have the lib do the conversion at parse time. How does that work, are you using a fromJSON instance on the type ?

Thanks

**Comment by ondrap** [comment]
Say you have: `[{"columns" : ["a", "b"]}, {"columns": ["c", "d"]}]`, then the parser should be like:
```
parser = arrayOf ("columns" .: (1 .! string)) -- Maybe there could be less parentheses
```
As for the timestamp - the `value` parser should work.
