### ISSUE TITLE
json-stream-0.3.0.3 test suite failure

### ISSUE THREAD

**Issue by peti** [ondrap/json-stream#2]
Please see http://hydra.cryp.to/build/783489/log/raw for a complete build log that shows the error messages.

**Comment by ondrap** [comment]
Fixed in @c0a6233153a15bebee66b06fd93734f98857854d
Wrongly written test, 'show' performs probably differently for different versions of some package. Fixed.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by ondrap** [comment]
I just did it - I wanted to add some functionality before doing a new release. Hopefully this time I got everything right...

**Comment by peti** [comment]
Thank you very much: http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellngPackages.json-stream.x86_64-linux.
