### ISSUE TITLE
Leaving JSON strings encoded as ByteStrings?

### ISSUE THREAD

**Issue by vdukhovni** [ondrap/json-stream#22]
I am using this module (thanks!) to process compressed files of up to 16GB in size whose uncompressed content can be up 100GB.  The files contain DNS data in A-label form, which is naturally all ASCII.  Given the quantity of data being processed, performance matters, and I'm currently paying the cost of having the DNS names converted to `Text` just long enough for me to convert them back to `ByteString`again, which is the form in which I need to process them further.

Is there a chance that a pair of `byteString`/`safeByteString` parsers could be added, that directly return the UTF-8 JSON payload without conversion to `Text`?

**Comment by ondrap** [comment]
That's not that easy, actually... the strings in JSON can contain escaped characters (e.g. \n, but also \uxxxx as some unicode sequence). I think it would be possible to create something like 'rawByteString' that would contain the raw unencoded string; if your data contains only ascii, that should probably work

The only thing is that the short strings get decoded quite early in the process; I would have to push them further to the parser and do the decoding there, but it seems doable.

**Comment by vdukhovni** [comment]
Thanks for the feedback, yes delayed conversion would be great, if it does not impose unreasonable costs on users who ultimately want Text.  I'd prefer to get the raw "escaped" strings as they are, and have the option of calling unescape myself, via a new parser primitive that skips delayed unescaping, if that turns out to be something that you're willing to support.

Part of the issue here is I guess that, sadly, Haskell's `Text` is using the obsolete UTF-16, while the world has moved on to UTF-8. If Text were UTF-8 that could be recast as an ASCII bytestring in place (that is UTF-8 decoding were a NOOP, that just yields the same memory as a different type), then I would not need to care as much...

**Comment by ondrap** [comment]
I think there is some difference between Text and ByteString in using pinned vs unpinned memory (one is using ForeignPtr, the other does not - I'm not an expert on this), so even if Text was in utf-8, it wouldn't quite work as a bytestring.
Anyway, on a first sight it seems it should generally work. I'm just thinking whether I should expose it as a lazy bytestring or a strict one; the strings can be quite long and the way they are processed is more like a lazy variant, most strings will end up strict anyway...

**Comment by ondrap** [comment]
I have just pushed to the repository a version that should support `byteString` and `safeByteString` parsers. It has a very slight negative impact on performance of some decoding. Can you give it a try if it works better for you?

**Comment by vdukhovni** [comment]
I made some measurements, as part of a workload that isn't just the parser, but processes the whole file, decompressing the data, and filtering the extracted JSON values.  This yields a somewhat lower impact from improvement in just the JSON performance.

With the parser returning `Text` the runtime for 1GB compressed file was:
```
real    2m6.266s
user    4m27.403s
sys     0m26.229s
```
With the parser directly returning `ByteString` the runtime was:
```
real    1m52.199s
user    4m2.652s
sys     0m19.914s
```
Which is about a `15%` reduction in the runtime.  It is not bad, and perhaps I could tune other parts of the workload further, but it is also not dramatic (factor or 2 or better).  So if I decide to drop this feature, I'll understand, but perhaps `O(15%)` is worth the effort...

**Comment by avanov** [comment]
I'd like to see it as an option
