### ISSUE TITLE
Overconsumption of input for consecutive string literals

### ISSUE THREAD

**Issue by Cajunvoodoo** [ondrap/json-stream#37]
Given a datatype such as the following:
```haskell
data MyData 
  = Foo
  | Bar
  deriving stock (Show, Generic)

$( deriveJSON
    defaultOptions
      { sumEncoding = UntaggedValue
      , constructorTagModifier = fmap Char.toLower
      }
    ''MyData
 )
```
decoding an input such as:
```json
"foo""bar"
```
results in 
```
ParseYield Foo (ParseDone "")
```
after running
```haskell
runParser' @MyData value "\"foo\"\"bar\""
```
meaning the following `"bar"` is erroneously consumed. This also occurs for any other data after the `"foo"`, not just string literals.

**Comment by ondrap** [comment]
Fixed. This is OK for strings, it still doesn't work for numbers/bools/nulls (would need some larger changes in the tokenizer to make this possible); there used to be some spec that a JSON should be either array or object, so I will keep it that way.
