### ISSUE TITLE
function of the ParseDone constructor

### ISSUE THREAD

**Issue by michaelt** [ondrap/json-stream#8]
This is no doubt a dumb question, and arises from my not having studied the way the `Parser` type works.  I was trying to figure out how to feed a streaming bytestring in the sense of https://hackage.haskell.org/package/streaming-bytestring and couldn't figure out how I should properly use the `ParseDone` constructor. This makes sense to me if I have a `Parser a` and am feeding a succession of bytestring chunks to it, in the hope of finally getting an individual `a`. Then I get the rest of the last chunk back. So, for example, I can then apply a different parser to the rest of the chunk and whatever other supply of chunks I have, as one does with any parsing library.

But the `parseByteString` and especially `parseLazyByteString` functions from this library return a list.  If I follow the lazy bytestring example, I get something like:

    import Data.JsonStream.Parser
    import Data.Aeson.Types (Value(..))
    import Data.ByteString.Streaming (ByteString,chunk, nextChunk)
    import Streaming
    import qualified Streaming.Prelude as S

    -- Randomly chosen information-preserving type
    -- Should this be like Pipes.Binary etc. (Either (DecodingError, ByteString m r) r)?
    type Results m r = Either (String, ByteString m r) (ByteString m r)

    parseStreaming :: Monad m => Parser a -> ByteString m r -> Stream (Of a) m (Results m r) 
    parseStreaming p0  = loop (runParser p0)  where
      loop parser q = case parser of
        ParseDone bs         -> return $ Right (chunk bs >> q) -- why don't I start again?
        ParseFailed e        -> return $ Left (e, q)
        ParseYield a parser' -> do 
          S.yield a
          loop parser' q
        ParseNeedData cont  -> do
          e <- lift $ nextChunk q
          case e of
            Left r            -> return $ Left ("Ran out of data",return r)
            Right (bs', more) -> loop (cont bs') more

I hope this is fairly intelligible. It would be exactly the same for a pipes version (`Pipes.next` would be used where `nextChunk` is used here); the type would be

    parseProducer :: Monad m
                            => Parser a
                            -> Producer ByteString m r 
                            -> Producer a m (Results m r) 

The question is, how are you envisaging the original bytestring/bytestream/chunk producer, at least in the case where there is no parse failure? What is the role of the left-over material?  Is it that the original stream starts with a single piece of json, an array for example, followed by some other material that will be parsed in some other way?  

It seems natural if I am looking to get a `[a]` from a `Parser a` (rather than a `Parser [a]`) that the parser will continue by repeating the original parser until things break down or the bytestring ends. 

I hope this question isn't too opaque.

**Comment by michaelt** [comment]
I meant to draw attention to the case for `ParseDone` in the code above. In one way of interpreting your intention, it would be natural to begin again with the original parser.

**Comment by michaelt** [comment]
Maybe the question is clearer if I ask, when I write 

    ParseDone bs         -> return $ Right (chunk bs >> q) 

is the thought that I have arrived at the end of the long json expression parsing began with, so that here at least it means `EndOfJsonExpression bs` or something like that.  It is seeming to me that that must be the right answer.

**Comment by ondrap** [comment]
I am not familiar with streaming-bytestring package. Yes, the `ParseDone` is basically something like end of top level expression. The reason `parseByteString` returns a list is that it can return 0 or more items. In the case of the parser being e.g. `value` it can be 0 or 1 (the `value` may not match the input data), in case of `arrayOf value` it can be 0 or more. 
The `parseByteString` is just a convenience function, the idea is that sometimes on the input you get data like:

    {'command': 1}{'command':2}{'command':3}
and sometimes you may get:

    [{'command':1},{'command':2},{'command':3}]

In the first case after parsing some expression (e.g. `"command" .: integer`), you will get `ParseDone "{'command':2}{'command':3}"` as a final result - and you can restart parsing if you wish (or run something different on the remaining data). In the second case, you would parse `arrayOf ("command" .: integer)` and you will get successive yields.

**Comment by michaelt** [comment]
I'm trying to implement a binding for pipes and 'streaming-bytestring' both, using pipes-aeson as a model. In theory a top-level 'entity' should be an array or object, as is emphasized at http://hackage.haskell.org/package/pipes-aeson-0.4.1.4/docs/Pipes-Aeson.html#v:decode  It's a little hard to make some of these distinctions if you presuppose that.  I will try to work on this more this afternoon. I'm just trying to figure out what types functions like Pipe.Aeson.decode and Pipes.Aeson.decoded should have. Because aeson doesn't stream, 

    Pipes.Aeson.decode 
      ::  (Monad m, FromJSON a)
      => Producer ByteString m x 
      -> m (Maybe (Either DecodingError a), Producer  ByteString m x)

will produce a single value, but it is always an array or object, and it waits for the end of the json 'entity'. In the present context, we want to stream the elements (or with your additional parsing framework, various sub-elements and so on) , particularly in the case of arrays. Whatever we are doing it will come to an end with the top level json thing. Meanwhile there is a function like ` Pipes.Aeson.decoded` which expects indefinitely many distinct json entities from a stream of bytes, and keeps parsing them until it crashes or it gets to the end of the file. It's a little hard to see what behavior is right for this library, where we hope to stream the elements of an array, or sub-items and so on.  

The problem will be the same with all the streaming libraries.

**Comment by ondrap** [comment]
I'm not sure about Pipes.Aeson, but an example how to use json-stream with Pipes is here:

https://gist.github.com/joelthelion/7d4d4b44120607b63035

**Comment by michaelt** [comment]
Right, this is a perfectly intelligible direct use of the `ParseOutput` constructors in connection with pipes,
but we are looking for a way of using the library with streaming types that does not directly use these constructors, but only the Parsers you define. It defines a pipe, which is fine for its purposes (which seems originally to have been to observe the operation of the parser). But the library function one is
looking for would be a function producer -> producer, though this distinction is subtle. If I were writing such a function *for arrays only* I would write:


    type PResult m r = Either (String, Producer B.ByteString m r)  (Producer B.ByteString m r)

    stream_array :: Monad m => Producer B.ByteString m r -> Producer Value m (PResult m r)
    stream_array = loop (runParser (arrayOf value) :: ParseOutput Value) where 
      loop p producer = case p of
        ParseFailed err     -> return (Left (err,producer))
        ParseYield value p' -> yield value >> loop p' producer
        ParseDone remaining -> return (Right (yield remaining >> producer))
        ParseNeedData cont  -> do
          e <- lift $ next producer
          case e of
            Left r -> return (Right (return r))
            Right (b,rest) -> loop (cont b) rest

Then the user could write the equivalent of the above, more or less, as 

     main = runEffect $ void (stream_array (Bytes.hGet 100 stdin))
                        >-> randomSampler
                        >-> P.map (BL.toStrict . A.encode) 
                        >-> P.map (\bs -> B.snoc bs '\n')
                        >-> Bytes.stdout
        where
       randomSampler = do
        val <- lift (randomIO :: IO Float)
        tmp <- await
        when (val < 0.01) $ yield tmp
        randomSampler

      -- $ cat ../json-stream/benchmarks/json-data/numbers.json | ./jstreampipe
      -- 1246.2060578215462
      -- 400289043093038200
      -- 187533421853308940000
      -- 248012950401001030000
      -- 20464419388347500000000000
      -- 207518534041199930000000000000
      -- 8513198457439368000000000000000000

(Crazy fast, by the way!)

I'm trying to figure out what the ideal version of `stream_array` would be for general use with your parsers and parser combinators, and the premise that we are only to apply it to 'top level' arrays or objects. I think it will sink in if I fiddle around more ...

**Comment by michaelt** [comment]
I meant to say, I think I figured the intended behavior out, and included a function for applying a json-streams parser to an effectful bytestring. Here is the demo program and ancillary remarks from the relevant module https://github.com/michaelt/streaming-utils/blob/master/Data/ByteString/Streaming/Aeson.hs#L10
